name: Mon premier workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    VARIABLE_NAME: value
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Listing files
          run: ls -al
  

